name = "solsync-lite"
main = "worker.js"
compatibility_date = "2025-09-14"
workers_dev = true

# R2 bucket binding (create this bucket first or via CLI)
[[r2_buckets]]
binding = "BUCKET"            # must match env.BUCKET in worker.js
bucket_name = "solsync-lite"  # must exist in your account

[vars]
# Your public front-end origin (R2 static site)
ALLOWED_ORIGIN = "https://pub-3063a45b808246b985290548b748f25c.r2.dev"
MAX_BYTES      = "104857600"  # adjust if you want larger
TTL_SECONDS    = "1800"       # link lifetime before first download



